### ISSUE TITLE
Некорректный спецификатор доступа

### ISSUE THREAD

**Issue by truenorthpaul** [melnyk-a/FileExplorer#2]
Спецификаторы доступа должны быть как можно более защищенными для каждого члена класса или структуры. В качестве исключения можно использовать `public` вместо `internal` если весь тип содержащий данный член помечен спецификатором `internal`.

Свойства (`set` часть), для которых данное правило не соблюдается:
- `FileExplorer.Models.Managers.CreatedEntries.CreatedEntriesManager.Items`.

**Comment by melnyk-a** [comment]
а как установить его private если это требование интерфейса?

**Comment by truenorthpaul** [comment]
Не увидел, что это было требованием интерфейса. Тогда здесь другая проблема. Непонятно, зачем в интерфейсе это свойство обладает `set` частью. Это позволяет переписать весь объект коллекции. Обычно, когда свойство является коллекцией, то класс-менеджер может просто выдавать наружу `get` часть, но через интерфейс, позволяющий модификации (например, `ICollection`), а класс-провайдер по интерфейсу более базовому (например, `IEnumerable`). К тому же, в проекте нигде `set` часть не используется.

Также можно было бы использовать явную реализацию интерфейса для этого свойства, что сделало бы его доступным для использования только через интерфейсную переменную.
